create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null check (price > 0),
  old_price integer not null check (old_price > 0),
  emoji text not null default '🔧',
  color text not null default 'green',
  image text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  items jsonb not null,
  total integer not null check (total > 0),
  status text not null default 'Order received',
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "public can read active products" on public.products;
drop policy if exists "public can create products" on public.products;
drop policy if exists "public can deactivate products" on public.products;
drop policy if exists "public can create COD orders" on public.orders;
drop policy if exists "admin can update order status" on public.orders;

create policy "public can read active products" on public.products for select to public using (active = true);
create policy "public can create COD orders" on public.orders for insert to public with check (true);
create policy "admin can update order status" on public.orders
  for update to authenticated using (true) with check (true);
